### PR TITLE
changed media to media_data, implemented chunked upload

### PR DESCRIPTION
**Pull request by Francesco149**
changed media to media_data, which fixes gifs being uploaded as static images

### CODE REVIEW

**Comment by Francesco149** [comment]
not sure why the travic ci build failed, tests pass just fine on my end.

**Comment by ChimeraCoder** [comment]
@Francesco149 the Travis CI server doesn't have Twitter credentials (because those are rate-limited and would result in tests that are both slow and flaky). I have an http-mock-tests branch that uses mock responses for these; I was planning on merging it today. Once I merge that, I'll rerun the Travis build for this PR, and it'll presumably pass.

Sorry for the confusion - I didn't realize Travis was going to start testing PRs immediately, but this should all be fixed within a few hours.

**Comment by Francesco149** [comment]
ah nice travis is fixed

**Comment by ChimeraCoder** [comment]
Merged - thanks for the patch!

**Pull request merged**
