### PR TITLE
Automatically deflate based on Content-Encoding

### LINKED ISSUE #170: Binary log line spewed from basic logger
I just set 

    api.SetLogger(anaconda.BasicLogger)

I got this line:

    2016/12/13 19:33:15 [Get https://api.twitter.com/1.1/followers/list.json?cursor=-1 returned status 429, x��VJ-*�/*V���V�M-.NLOU�R
    J,IU����,QH�HNMMIMQ�QJ�OJZX�����0�B]

Kind of worrying.

### PR DESCRIPTION
**Pull request by andrewgaul**
Twitter returns deflate data despite the client only requesting gzip
data.  net/http automatically handles the latter but not the former:
https://github.com/golang/go/issues/18779

Fixes #170.

### CODE REVIEW

**Comment by ChimeraCoder** [comment]
Thanks!

Out of curiousity, do you know under which circumstances Twitter returns deflated responses?

**Comment by andrewgaul** [comment]
Sorry I'm not exactly sure how I encountered this issue since I worked on it some months ago.

**Comment by ChimeraCoder** [comment]
No worries. Thanks again for the patch!

**Comment by andrewgaul** [comment]
I reproduced the symptoms with this call:

```
2017/09/05 00:00:30 Could not authenticate: Get https://api.twitter.com/1.1/friends/list.json?cursor=1538070094339682341&tweet_mode=extended returned status 503, x��VJ-*�/*V���V�M-.NLOU�R�/K-RHN,HL�,�T�QJ�O
�������N
```

**Comment by Gurpartap** [comment]
I get deflate data responses randomly every so often. Thanks for the fix @gaul @ChimeraCoder !

**Pull request merged**
