### PR TITLE
[stream] auto reconnect stream, add logging possibilities, and quit stream gracefully

### PR DESCRIPTION
**Pull request by azr**
Hello there,

The commit are pretty clear :)

Thanks !

### CODE REVIEW

**Comment by azr** [comment]
it kinda also contains https://github.com/ChimeraCoder/anaconda/pull/62

I'm gonna add some other things too :)

**Comment by azr** [comment]
Hello there,

I just rebased it !

It works fine :) so far it's been running non stop for 3 days ( another thing from pipeline caused restart )

cheers

**Comment by ChimeraCoder** [comment]
Thanks! This has been merged as of 964821c05001e5a38dd234d681ce9a929858481a.

**Comment by azr** [comment]
Cool ! :) 

I was thinking the pseudo exponential backoff I did in `loop` was kind of ugly.

May be you have an Idea ? or we could use this one : https://godoc.org/github.com/cenkalti/backoff ?

**Pull request closed without merging**
