### PR TITLE
Added Block/Unblock User functionality 

### PR DESCRIPTION
**Pull request by BharathMG**
- GET blocks/list - Users who are blocked.
- GET blocks/ids - User ids who are blocked.
- POST blocks/create - Block an user
- POST blocks/destroy - Unblock an user

### CODE REVIEW

**Comment by BharathWork** [comment]
Added POST blocks/create - Blocks an user with screen name or id.

**Comment by BharathMG** [comment]
Ping !

**Comment by ChimeraCoder** [comment]
Thanks! Merged as of 4918dc0164fdd60397972497eb4a6436c4168634.

I made one small change: I changed the spelling from `UnBlock` to `Unblock`. I'm open to discussion on this, but at first glance, the former strikes me as a bit jarring, and I believe the lowercase 'b' is more in line with field casing in Go.

Thanks for the patch!

**Comment by BharathMG** [comment]
Yes ! No problem with that :) :+1:

**Pull request closed without merging**
