### PR TITLE
Added email field

### PR DESCRIPTION
**Pull request by Fyb3roptik**
Added the every missing email field

### CODE REVIEW

**Comment by muesli** [comment]
Which endpoint's response do you see that email field in? I can't seem to find it in their docs.

**Comment by Fyb3roptik** [comment]
It is after the user allows access. It sends back Email if they have one

**Comment by alexbilbie** [comment]
Please can this be merged?

**Comment by muesli** [comment]
Looks good to me, but needs a rebase / squash.

Also, the appveyor check is somehow stuck. @ChimeraCoder: This seem to be a problem for all PRs right now, any idea what's going on?

**Comment by ChimeraCoder** [comment]
@muesli I'm not sure, but it seems to be consistently the "branch" check that gets stuck, not the "pr" check. Since the latter's what we need, I disabled the branch check as a requirement for merging.

**Pull request merged**
